application: jeeqsy
version: vote_refactoring
runtime: python27
api_version: 1
threadsafe: false

builtins:
  - remote_api: on
  - deferred: on

libraries:
- name: jinja2
  version: 2.6
- name: django
  version: 1.3

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static
  expiration: 7d

- url: /cron/.*
  script: sanity_check_cron.py

#- url: /remote_api
#  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py

- url: /oauth2callback
  script: oauth2client.appengine.application

- url: /admin/.*
  script: admin.py
  login: admin

- url: .*
  script: jeeqs.py

