application: jeeqsy
version: alpha
runtime: python27
api_version: 1
threadsafe: no

builtins:
  - remote_api: on

libraries:
- name: django
  version: latest

- name: jinja2
  version: latest

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static
  expiration: 7d

#- url: /remote_api
#  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py

- url: /admin/.*
  script: admin.py
  login: admin

- url: .*
  script: jeeqs.py
